services:
  db:
    image: mysql:8.0
    container_name: dorivo_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  cache:
    image: redis:7-alpine
    container_name: dorivo_redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: dorivo_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
    env_file:
      - .env

volumes:
  mysql_data: